import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "./components/Navbar";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs";

import { AuthProvider } from "@/hooks/useAuth";
import { QueryProvider } from "@/components/providers/QueryProvider";
import { ToasterProvider } from "@/components/providers/ToasterProvider";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50">
        <QueryProvider>
          <AuthProvider>
            <Navbar />
            <main className="flex-1 container mx-auto px-4 py-8">
              <Breadcrumbs />
              {children}
            </main>
            <ToasterProvider />
          </AuthProvider>
        </QueryProvider>
      </body>

    </html>
  );
}



